test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

scaleway:
  service: S3
  access_key_id: <%= ENV['S3_BUCKET_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_BUCKET_SECRET_KEY'] %>
  region: fr-par
  bucket: booklub
  endpoint: https://s3.fr-par.scw.cloud
